### ISSUE TITLE
TypeError: `default_name` type (<class 'list'>) is not a string type. 

### ISSUE THREAD

**Issue by SeekPoint** [junyu-Luo/chinese_word_segmentation_transformer#1]
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    main()
  File "train.py", line 119, in main
    estimator.train(input_fn=train_input_fn(tf_record_file, options))
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1188, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1146, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "train.py", line 69, in model_fn
    loss = create_model(features, labels, mode, config)
  File "train.py", line 59, in create_model
    logits, t_ids, config.label_smoothing, config.vocab_size_tar)
  File "G:\ub16_prj\bumblebee\DSX_NER\chinese_word_segmentation_transformer\model\metrics.py", line 64, in padded_cross_entropy_loss
    with tf.name_scope("loss", [logits, labels]):
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 6450, in __init__
    "pass this into the `values` kwarg." % type(default_name))
TypeError: `default_name` type (<class 'list'>) is not a string type. You likely meant to pass this into the `values` kwarg.

**Comment by SeekPoint** [comment]
change to
with tf.name_scope("loss", values = [logits, labels]):

can fix it
