### ISSUE TITLE
indices[8,4] = 6550 is not in [0, 6454)

### ISSUE THREAD

**Issue by SeekPoint** [junyu-Luo/chinese_word_segmentation_transformer#3]
2020-05-01 07:49:58.977383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 5:   N N N Y Y N Y
2020-05-01 07:49:58.977390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 6:   N N N Y Y Y N
2020-05-01 07:50:00.952463: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./out/model.ckpt.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[8,4] = 6550 is not in [0, 6454)
	 [[{{node model/Transformer/decode/embedding_shared_weights/embedding/GatherV2}}]]

**Comment by AOoligei** [comment]
hello,have you solve the problem,i meet the same problem,how did you do?[https://github.com/facebookarchive/CommNet/issues/4](url)

**Comment by prigioni** [comment]
> hello,have you solve the problem

hello,have you solve the problem?

**Comment by tai-yi-c** [comment]
hello, I have encountered the same problem.Have you solve it?
